apiVersion: v1
kind: Namespace
metadata:
  name: password-generator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-generator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: password-generator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: password-generator
    spec:
      containers:
      - image: harishgopi/password_generator:latest
        name: password-generator
        ports:
        - containerPort: 5000
        resources: 
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "50Mi"
            cpu: "50m"

---
apiVersion: v1
kind: Service
metadata:
  name: password-generator-service
spec:
  type: LoadBalancer
  selector:
    app: password-generator
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000